version: '#{build}'
image: 'Visual Studio 2019'
branches:
  only:
  - master
  - kptsky_testing
skip_tags: true
clone_depth: 1

environment:
  matrix:
   - configuration: x64
     BUILD_ARCH: x64
     BUILD_MSVC: msvc2019_64

   - configuration: Win32
     BUILD_ARCH: Win32
     BUILD_MSVC: msvc2019

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A %BUILD_ARCH% -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH=C:\Qt\5.15\%BUILD_MSVC% ..
  - cmake --build . --config Release

artifacts:
- path: build/build/Release/RcloneBrowser.exe

test: off
deploy: off
